name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"] # Add more versions as needed
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install uv (Unix)
        if: runner.os != 'Windows'
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install uv (Windows)
        if: runner.os == 'Windows'
        run: powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/0.5.22/install.ps1 | iex"

      - name: Build and install package
        run: uv build --editable .

      - name: Install test dependencies
        run: uv pip install pytest black

      - name: Run tests
        run: pytest . -vv

      - name: Lint with Black
        run: black --check .
