name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"] # Add more versions as needed
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build the package
        run: uv build

      - name: Run tests
        run: pytest . -vv

      - name: Lint with Black
        run: black --check .
